// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function() {
    if (this["catch"] == null) {
      p("What is bothering you?");
      form({
        "class": "catch create",
        method: "post",
        action: "/catches"
      }, function() {
        ol({
          id: "steps"
        }, function() {
          return li(function() {
            return input({
              name: "steps",
              type: "text",
              placeholder: "describe what is happenig, step by step",
              size: 128
            });
          });
        });
        return input({
          type: "submit",
          value: "save"
        });
      });
    } else {
      h1("Public profile of " + this.participant.name);
      if (this.username === this.participant.email) {
        form({
          "class": "profile update",
          method: "post",
          action: "/participants"
        }, function() {
          label({
            "for": "name"
          }, "How shall we address you in public?");
          input({
            type: "text",
            name: "name",
            value: this.profile.name
          });
          return input({
            type: "submit",
            value: "save"
          });
        });
      }
    }
    return coffeescript(function() {
      return jQuery(function($) {
        var list;

        list = $("#steps");
        list.sortable();
        list.disableSelection();
        return $("#steps li:last-child input[name=steps]").live("focus", function() {
          var item;

          item = $(this).parent().clone().hide();
          item.appendTo(list).fadeIn("slow");
          item.find("input").val("");
          return list.sortable("refresh");
        });
      });
    });
  };

}).call(this);
