// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function() {
    var _ref, _ref1, _ref2;

    if (this.participant == null) {
      p("Hello! Thanks for authenticating.");
      p("Before we let you play with us, we really need to know one thing.");
      form({
        "class": "profile create",
        method: "post",
        action: "/participants"
      }, function() {
        label({
          "for": "name"
        }, "How shall we address you in public?");
        input({
          type: "text",
          name: "name"
        });
        return input({
          type: "submit",
          value: "save"
        });
      });
    }
    h1("Public profile of " + ((_ref = this.participant) != null ? _ref.name : void 0));
    if ((_ref1 = this.participant) != null ? _ref1.slug : void 0) {
      return p("Slug is " + ((_ref2 = this.participant) != null ? _ref2.slug : void 0));
    } else {
      p("You need to create one before you can interact with others. Here's your chance :)");
      return p(function() {
        text("You don't want to? No problem here. Just ");
        a({
          "data-signout": true,
          href: "#"
        }, "logout");
        return text(" and we'll be fine with you.");
      });
    }
  };

}).call(this);
